// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eqfbraacoapzwjzrvszu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVxZmJyYWFjb2FwendqenJ2c3p1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzNzI5OTAsImV4cCI6MjA2NTk0ODk5MH0.Bg5f0JKu7bXroxzWZv_rnY7V-VsqiF995poVv10zMQo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});